### ISSUE TITLE
Confirm or implement Stripe integration

### ISSUE THREAD

**Issue by kenton** [boomerdigital/solidus_marketplace#11]
For MVP, the Market Maker will handle payments for all orders. So we need one Stripe integration that works across the entire store, tied to the store owner.  This may already exist or be simple to implement, so this task may just be confirmation of that, else we need to implement it.

**Comment by kenton** [comment]
I don't see any reason why we can't just suggest using [solidus_gateway](https://github.com/solidusio/solidus_gateway) for this.

But should we:

1. incorporate that into this gem so it's present automatically once someone installs this gem? or 
2. just suggest they install solidus_gateway in order to handle the payments stuff?

I'd say we go with option 1, just to deliver a more complete solution.

Thoughts?

 @pmn4

**Comment by pmn4** [comment]
_I_ am totally fine w/this since I cannot imagine a Solidus projects without solidus_gateway. are there other popular payments gems out there? would you have to write a bunch of code without it?
IMO, I'd like to see this gem work out of the box for someone spinning up a new project, because (I assume!) this will cover the majority of projects using the gem (i.e., it seems less likely that an established project would be adding this gem. existing projects probably already have some sort of solution?). And if that's the case, adding this dependency seems fine

**Comment by kenton** [comment]
PR https://github.com/boomerdigital/solidus_marketplace/pull/44
